theme: jekyll-theme-cayman
title: Samuel Rosales - Data Science Portfolio
description: Hi! My name is Samuel. Take a look at my porfolio! Click in each header to see more about each project. If you want to see the scripts I used you’ll find them inside of each project.
